on: push

jobs:
  test_and_compile:
    runs-on: ubuntu-latest
    name: test and compile
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y pandoc lmodern wkhtmltopdf
      - run: mkdir -p output
      - run: make test
      - run: make
      - name: Move generated files to output folder
        run: |
          find . -type f -not -path "./output/*" -exec mv {} output/ \;
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Commit and push changes
        run: |
          git add output/*
          git commit -m "Add generated files to output folder"
          git push
