on: push

jobs:
  test_and_compile:
    runs-on: ubuntu-latest
    name: test and compile
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y pandoc lmodern wkhtmltopdf
      - run: mkdir -p output
      - run: make test
      - run: make
      - uses: actions/upload-artifact@v3
        with:
          name: output
          overwrite: true
          path: output/
      - name: Move PDF to output folder
        run: mv generated.pdf output/
      - name: Commit and push PDF
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add output/sample.pdf
          git add output/sample.html
          git commit -m "Add generated CV"
          git pus