on: push

jobs:
  test_and_compile:
    runs-on: ubuntu-latest
    name: test and compile
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y pandoc lmodern wkhtmltopdf
      - run: make test
      - run: make
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output/
      - uses: actions/download-artifact@v3
        with:
          name: docs
          path: docs/
      - name: update file and push to remote
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "Update CV"
          git push
